### ISSUE TITLE
Running from homedir crashes

### ISSUE THREAD

**Issue by kootenpv** [sametmax/devpy#1]
```
pascal@MBP:~ $ python3.6
Python 3.6.0 (v3.6.0:41df79263a11, Dec 22 2016, 17:23:13)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import devpy.develop as log

Traceback (most recent call last):

  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/devpy/develop/__init__.py", line 6, in <module>

    sys.modules['devpy.develop'] = dev_mode()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/devpy/__init__.py", line 14, in dev_mode

    return devpy.autolog()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/devpy/log.py", line 30, in autolog

    name = Path(sys.argv[0]).with_suffix('').name
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/pathlib.py", line 834, in with_suffix

    raise ValueError("%r has an empty name" % (self,))
ValueError: PosixPath('.') has an empty name
>>>
>>>
```

**Comment by sametmax** [comment]
Nice catch!

Fixed with b8bf5e1297ff3dca67279ad95c454e3449795aac
